// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqyx8-Pjwl6XQyUHtdCP1lEYEZ1rxyoio',
    appId: '1:1083272763876:web:54fedb2e654fdaa3594ff1',
    messagingSenderId: '1083272763876',
    projectId: 'focusdungeon',
    authDomain: 'focusdungeon.firebaseapp.com',
    storageBucket: 'focusdungeon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCysabBa7LxWHdpihR4mDiCsVzSEwy1Zzg',
    appId: '1:1083272763876:android:6422e5d064285fc2594ff1',
    messagingSenderId: '1083272763876',
    projectId: 'focusdungeon',
    storageBucket: 'focusdungeon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhPQoQ60pzoHfIZby79KjaucH5E_NEN4g',
    appId: '1:1083272763876:ios:72ba7ca4d0ea0f04594ff1',
    messagingSenderId: '1083272763876',
    projectId: 'focusdungeon',
    storageBucket: 'focusdungeon.firebasestorage.app',
    iosBundleId: 'com.example.focusDungeon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhPQoQ60pzoHfIZby79KjaucH5E_NEN4g',
    appId: '1:1083272763876:ios:72ba7ca4d0ea0f04594ff1',
    messagingSenderId: '1083272763876',
    projectId: 'focusdungeon',
    storageBucket: 'focusdungeon.firebasestorage.app',
    iosBundleId: 'com.example.focusDungeon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqyx8-Pjwl6XQyUHtdCP1lEYEZ1rxyoio',
    appId: '1:1083272763876:web:af7ac5ff6a3d00a9594ff1',
    messagingSenderId: '1083272763876',
    projectId: 'focusdungeon',
    authDomain: 'focusdungeon.firebaseapp.com',
    storageBucket: 'focusdungeon.firebasestorage.app',
  );
}

